version: "3.7"

services:
    app:
        image: symfony-fullstack_app
        container_name: app-container
        volumes:
            - phpsocket:/var/run/php

    web:
        image: symfony-fullstack_web
        container_name: web-container
        ports:
            - 8050:80
        volumes:
            - phpsocket:/var/run/php
        depends_on:
            - app

    other_api:
        image: dotronglong/faker:stable
        volumes:
            - ./mock:/app/mocks
        ports:
            - 3030:3030

volumes:
    phpsocket:
